version: "3"
services:
  db:
    image:  mysql:8.0.26
    restart:  always
    platform: linux/amd64
    command:
      -  --lower_case_table_names=1
      -  --character-set-server=utf8bm4
      -  --collation-server=utf8bm4_unicode_ci

    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root1234!!
      - TZ=Asia/Seoul
    volumes:
      - /Users/wngud/Desktop/Spring/PraticeSpring/Submysql